ALTER TABLE FACTURA DROP CONSTRAINT FK_FACTURA_CLIENT_ID
ALTER TABLE LINIIFACTURI DROP CONSTRAINT FK_LINIIFACTURI_SERVICIU_IDSERVICIU
ALTER TABLE LINIIFACTURI DROP CONSTRAINT FK_LINIIFACTURI_FACTURA_NRFACTURA
DROP TABLE CLIENT CASCADE
DROP TABLE SERVICIU CASCADE
DROP TABLE FACTURA CASCADE
DROP TABLE LINIIFACTURI CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
